all: animal

animal:
	rustc $@.rs

generic_read:
	rustc $@.rs

buf_builder:
	rustc $@.rs

lifetime:
	rustc $@.rs

ref_cell:
	rustc $@.rs

r_dag:
	rustc $@.rs

pointer_test:
	rustc $@.rs

vec_stack:
	rustc $@.rs

clean:
	rm -rf pointer_test vec_stack r_dag ref_cell lifetime generic_read \
		buf_builder animal
